# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/desktop/COD_Labs/Lab2/Lab2_Q2/Lab2_Q2.srcs/sources_1/ip/RAM0/RAM0.xci
# IP: The module: 'RAM0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/desktop/COD_Labs/Lab2/Lab2_Q2/Lab2_Q2.gen/sources_1/ip/RAM0/RAM0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/desktop/COD_Labs/Lab2/Lab2_Q2/Lab2_Q2.srcs/sources_1/ip/RAM0/RAM0.xci
# IP: The module: 'RAM0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/desktop/COD_Labs/Lab2/Lab2_Q2/Lab2_Q2.gen/sources_1/ip/RAM0/RAM0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
