# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/desktop/COD_Labs/Lab4/Lab4_cpu - test/Lab4_cpu.srcs/sources_1/ip/instrcution/instrcution.xci
# IP: The module: 'instrcution' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/desktop/COD_Labs/Lab4/Lab4_cpu - test/Lab4_cpu.gen/sources_1/ip/instrcution/instrcution_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instrcution'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/desktop/COD_Labs/Lab4/Lab4_cpu - test/Lab4_cpu.srcs/sources_1/ip/instrcution/instrcution.xci
# IP: The module: 'instrcution' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/desktop/COD_Labs/Lab4/Lab4_cpu - test/Lab4_cpu.gen/sources_1/ip/instrcution/instrcution_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instrcution'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
