# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/desktop/COD_Labs/Lab5/Lab5_q1/Lab5_q1.srcs/sources_1/ip/memory/memory.xci
# IP: The module: 'memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/desktop/COD_Labs/Lab5/Lab5_q1/Lab5_q1.gen/sources_1/ip/memory/memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/desktop/COD_Labs/Lab5/Lab5_q1/Lab5_q1.srcs/sources_1/ip/memory/memory.xci
# IP: The module: 'memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/desktop/COD_Labs/Lab5/Lab5_q1/Lab5_q1.gen/sources_1/ip/memory/memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
