# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/desktop/COD_Labs/Lab4/Lab4_cpu/Lab4_cpu.srcs/sources_1/ip/Memory/Memory.xci
# IP: The module: 'Memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/desktop/COD_Labs/Lab4/Lab4_cpu/Lab4_cpu.gen/sources_1/ip/Memory/Memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Memory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/desktop/COD_Labs/Lab4/Lab4_cpu/Lab4_cpu.srcs/sources_1/ip/Memory/Memory.xci
# IP: The module: 'Memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/desktop/COD_Labs/Lab4/Lab4_cpu/Lab4_cpu.gen/sources_1/ip/Memory/Memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
